apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Y2kEtdx6wdbo8M53Ex3bRmLuklmXyxLatIoPrpxoFFOL3Vza/11GVQaA8CViUYwHTnxWGyFYOTzTHSdI4wcu2v4=,iv:UVUOAr6x/KGl5uJo58+mUNbUTo1btOQnFS7Qm95sAl0=,tag:FyiM8Bou3jVtSCV4xG0uuw==,type:comment]
    #ENC[AES256_GCM,data:KEjSn1IwzOb7RC9tLOMlTH+d3Tj6V5f4WqIMPk8QSn+BXxRH3QlBxgqzSgs=,iv:lVcOjodsFWCpo/tGp404aTq9dWguCrH360NeG4QVy8Q=,tag:AlqxijYQ5ex1Yu83JYTjXw==,type:comment]
    VIP: ENC[AES256_GCM,data:G4DeznbY8hk0gsY0fg==,iv:Oyykx8kMDh8WTCq9bPqHYoWSM6H9IrNX6rT5E9x7jpA=,tag:ogB0xS7ZZYYqC2PpIs2Uiw==,type:str]
    #ENC[AES256_GCM,data:GaLqcqginc3FnnOYI+xePBB3zUqSNmGNb1I=,iv:82a3ziZUG5RNc2rZLaxxjg1zjpjA9AkXl7wIuHkQt6k=,tag:7qDiKHTADQ+/T+xwK5dI/w==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:oCiLvA/dadNxF1QDgg==,iv:HHfhLy64s6BOvblXjB1t/1ECe++JQ9DaPQhjuhHwcc0=,tag:vIsPs3SHBnc5MBKvlkIIrA==,type:str]
    #ENC[AES256_GCM,data:bwbgG1ZbiLE/WNTPkNPr5mqvU5oHJcbN492KGS0Z5EqhGw==,iv:OpaTgEzP/F3Q14v479d7kPOMgWOUbnuCSZ2LoMrCSdw=,tag:ebdTYTHMtR+8iS9pgOAsug==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:tqj8J7OGrng6aRU=,iv:IPMStndw9BAJObljoKPqG1ct7xHzYSGrw55/sTi3jPk=,tag:vr1KFtiIKGS6IwUn3yiY0Q==,type:str]
    #ENC[AES256_GCM,data:gaD32zkrrM0tn2eekgFezVD2ZAMSO3XmY+Bi3dCrJcIwdKY6zutrhJqSGlBKssE=,iv:ls9dch4nd2bo882hgDMBlNEMU6KBy869hxuUYb4BWuo=,tag:PUjyOEen+myFAF5QLA5qtg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:+8EgWZsABwSmizO4U5mV/nZvhtgN7LA5KFCF,iv:Pplyy0FanYWvwxceZSeaE/mFwTqRXwmQI4NE0g5d564=,tag:Fr+i/WlxcGr8gJlJ7Z9UyA==,type:str]
    #ENC[AES256_GCM,data:kh60ozMv6E9i8e5ViT5RSTgVtCdfiUCCwma0ggIA3niaaxGxIsD4J5Wjn1oJiEJ5bv9wdN6bQsRSg4LbmdTr1paktEfrrTIBzxPx8NgVuSI=,iv:le67jrregCWZ7IKT3IGKcK/lQnhBfwXl2+Tu0jl21oU=,tag:hWo28KW1tWltCvBmyz3fbA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Yj8UzcsvaRVzkQtDig==,iv:S8SDMfo0E8o/dNhLUPMwHvq6P39JT6xkLd2+/mWbn44=,tag:TBo1818VZD1X1QY3ZVofeA==,type:str]
    #ENC[AES256_GCM,data:ChnqH8MING9v3wln0yjKPWFM2vowk2tld7qqPtRFvhJD6bDV76f03GaZKOP4vMgLVHIb1ktwKdRWh9koo7vkkRcHWlE=,iv:3IqjVWcuVQQJezB2InOOrBkOmuC9q04vH0gdnOmsJmU=,tag:VY+H/nsD61tmkQbxOMT1iA==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:czc2+samwLi5rg6JOw==,iv:ym5j5h48J4/4OY44zE+ZUHNCYcXp9cSb1LM0M7dZ7jA=,tag:bS3u5w9agOxQJne1lkqxvw==,type:str]
    #ENC[AES256_GCM,data:F4eth0UBx/NldP6Q0H7HUWlkTrFy+B7+CpGupSIHOXE4BRGrAO08fJxoyu21Dy8K+h6RhLYFskQ=,iv:eYEnb4cmB+OIIwdaaDVhQD/Bc9QDtgUnIV3TMyAl2tM=,tag:K7OeBhRcUCRcDwvxkY6H2Q==,type:comment]
    #ENC[AES256_GCM,data:C8dVXmR+er3oX6KZKJLQMSei3p9YeQMgVg==,iv:LTQhlku4bwFJrKHUqRK5msPO5olEY15O9uzEP+wulP0=,tag:E+V8iHkt0v+E6kJdORpRcw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ZuZGMRAkM1naJzsZPjgVWA6nrRzujdVbUooCrnmGaANugrZSalLBGhAS2632rmzb4mRcifZUVw==,iv:IMIANbxQ2P8LtyikVS4U9XsIeYSp19fVW28fmMNjC7M=,tag:49Tbr97N1ovF8BSjwwdhbQ==,type:str]
    #ENC[AES256_GCM,data:hkSKtSP+0BftMxGbKg==,iv:PMjXB4Fch6x+iAtURqwIzISsW576nPvxzzRZUtHExT4=,tag:h6cCOqFSum4vCsJMB5t1oA==,type:comment]
    PODNET: ENC[AES256_GCM,data:5toDb5jUQmfB4O5YpA==,iv:zGZN+Si+q/tSCpUvdvkQUSw4ROIVUoUEwfo65FItYwQ=,tag:ktUiFiGKnZvjyTw+orJ1lA==,type:str]
    SVCNET: ENC[AES256_GCM,data:me3dZm0LwLS7hY2x4Q==,iv:Y7qO6fA+MhTo9/H4T/PRlWpgUMNyL/Z9xYKMqvSzogk=,tag:GrVqCmtFt1mUQdXpDVv8HQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18he6s77x0we5nrg0dgx9qan9h4aa5rrw3jnltyqgqljgsf5tjgzs02qc4k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSmFxd1BlajdGQm45a0N2
            YS9vKytpdFJMUWdUNUQyMmcvOGhPbkdaeVZVCnU2MW9jN3N2MTQxM2tvYVVNNkc3
            NlZOTmZGOVlPNXJUNmJuNzdaRVFZSlUKLS0tIFJySmhGOTVUMDYwMXNGamluRmRh
            VjVWV2NaSnp6QytvWmJNbUZGdTdmcFkKLeV59XDgu6qj1jVJ1OfS4lEAuW5Tr7Jg
            tqkGiShAQqGG6Yki1JioNSXcWL98s2srI6avPYinqEgTKrawtgLqrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-25T01:33:37Z"
    mac: ENC[AES256_GCM,data:VZQQUNbPLIsde0npeJVmU60eNfuTEw3rN8UyGe8e6zUbqhd5pLk+KvQ3JucumAeyy2IVWdoByr7kEzLS4jbIWd9lWfLURBluj27hXfLD7iNYXPXCjvq38HfW3Ebhl3h2mMDLQBEZHK1O5a4Y5VQL+YJz2WKDkH+AixcnX3huftU=,iv:dkWRRemLtY0KnwFzQlLl7eC6dJah1G4gX6YxWN3K8E8=,tag:ZltE8rhI1LWPQLFfRCbsEQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
